[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle API routes
[[redirects]]
  from = "/api/*"
  to = "https://web-production-da8f4.up.railway.app/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
